services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: dpg-d6rru57gi27c73coueb0-a
      - key: DB_USER
        value: tododb_v2jx_user
      - key: DB_PASSWORD
        value: 1y5Hf3KM63XI3Lqtk6KttGaFUt5gr53G
      - key: DB_NAME
        value: tododb_v2jx
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02230310.onrender.com