services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_HOST
        value: dpg-d7gs7f28qa3s73coo00g-a.singapore.render.com
      - key: DB_USER
        value: todo_database_zy21_user
      - key: DB_PASSWORD
        value: tMrl3eg090abZ8jB5AT39fFsPHLCWzea
      - key: DB_NAME
        value: todo_database_zy21
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02230310-1.onrender.com