services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        fromService:
          name: postgres-db
          type: pserv
          property: host
      - key: DB_USER
        fromService:
          name: postgres-db
          type: pserv
          property: username
      - key: DB_PASSWORD
        fromService:
          name: postgres-db
          type: pserv
          property: password
      - key: DB_NAME
        fromService:
          name: postgres-db
          type: pserv
          property: database
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    buildCommand: npm run build
    startCommand: nginx -g "daemon off;"
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com